allowCompoundWords: true
dictionaries:
  - bash
  - companies
  - cpp
  - cpp-legacy
  - en-gb
  - en_us
  - fonts
  - git
  - npm
  - softwareTerms
enableGlobDot: true
features:
  weighted-suggestions: true
globRoot: ${cwd}
ignorePaths:
  - .git/objects
  - .github/CODE_OF_CONDUCT.*
  - cspell.config.yml
language: en,ja
useGitignore: true
version: "0.2"
words:
  - alcom
  - alsa
  - antlr
  - apic
  - biosapic
  - bioslogofadein
  - broot
  - cfprefsd
  - clmv
  - dind
  - glab
  - gotop
  - hpet
  - hwvirtex
  - ioapic
  - ionescu
  - iZotope
  - karabiner
  - kito
  - kotoeri
  - kurone
  - lporg
  - mackup
  - maxon
  - meslo
  - modifyvm
  - mswin
  - nmap
  - nyancat
  - osascript
  - pfind
  - pgrep
  - pkill
  - plantUML
  - siri
  - sorin
  - spctl
  - usbxhci
  - tldr
  - usbxhci
  - vbguest
  - vtxux
  - vtxvpid
  - wkhtmltopdf
  - zprezto
