- name: Install the anyenv
  homebrew:
    name: anyenv
    state: present

- name: Create a folder for anyenv
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  with_items:
    - .config
    - .config/anyenv

- name: Initialize the anyenv
  git:
    repo: "https://github.com/anyenv/anyenv-install.git"
    dest: "{{ ansible_env.HOME }}/.config/anyenv/anyenv-install"
    force: true

- name: Detect a anyenv setting file
  stat:
    path: ~/.zsh.d/anyenv
  register: anyenv

- name: Deploy a anyenv setting
  template:
    src: anyenv
    dest: "{{ ansible_env.HOME }}/.zsh.d/anyenv"

- name: Initialize the nodenv
  command: anyenv install nodenv -s
  register: nodenv
  changed_when: "nodenv.stdout != ''"
