- name: Install the Links
  homebrew:
    name: links
    state: present

- name: Install the Desktop browsers
  homebrew_cask:
    accept_external_apps: true
    name: "{{ item }}"
    state: present
  with_items:
    - cocoarestclient
    - firefox
    - google-chrome
