# App Store: OneDrive

- name: Install the Cloud storage tools
  homebrew_cask:
    accept_external_apps: true
    name: "{{ item }}"
    state: present
  with_items:
    - adobe-creative-cloud
    - dropbox
