- name: Install the utils for devices
  homebrew_cask:
    accept_external_apps: true
    name: "{{ item }}"
    state: present
  with_items:
    - homebrew/cask-drivers/drobo-dashboard
    - amorphousdiskmark
    - haptickey
    - nosleep
    - sidequest
    - soundflower
