- name: Install the Android Studio
  homebrew_cask:
    name: android-studio
    state: present

- name: Install the CLI for AWS
  homebrew:
    name: awscli
    state: present

- name: Install the NVM
  homebrew:
    name: nvm
    state: present

- name: Install the .NET Core
  homebrew_cask:
    name: dotnet-sdk
    state: present

- name: Install the PowerShell Core
  homebrew_cask:
    name: powershell
    state: present

- name: Install the Visual Studio
  homebrew_cask:
    name: visual-studio
    state: present

- name: Set the dev utils completion to .bash_profile
  lineinfile:
    dest: ~/.bash_profile
    regexp: "bash_completion.d\/{{ item }}$"
    line: "source /usr/local/etc/bash_completion.d/{{ item }}"
  with_items:
  - aws_bash_completer
  - nvm
