- name: Install the vim
  homebrew:
    name: vim
    state: present

- name: Install the editors
  homebrew_cask:
    accept_external_apps: true
    name: "{{ item }}"
    state: present
  with_items:
    - atom
    - boost-note
    - grammarly
    - notion
    - sublime-text
    - visual-studio-code

- name: Install the plugins for Visual Studio Code
  command: "code --install-extension {{ item }}"
  register: code
  changed_when: '"already installed" not in code.stdout'
  with_items:
    - aaron-bond.better-comments
    - alefragnani.Bookmarks
    - asvetliakov.snapshot-tools
    - britesnow.vscode-toggle-quotes
    - chrislajoie.vscode-modelines
    - coenraads.bracket-pair-colorizer-2
    - davidanson.vscode-markdownlint
    - dbaeumer.vscode-eslint
    - denco.confluence-markup
    - donjayamanne.githistory
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - eg2.vscode-npm-script
    - esbenp.prettier-vscode
    - felipe.nasc-touchbar
    - fallenwood.vimL
    - jebbs.plantuml
    - kelvin.vscode-sshfs
    - kumar-harsh.graphql-for-vscode
    - marcostazi.vs-code-vagrantfile
    - mikestead.dotenv
    - ms-azuretools.vscode-docker
    - MS-CEINTL.vscode-language-pack-ja
    - ms-vscode.js-debug-nightly
    - ms-vscode.powershell
    - ms-vscode.vscode-typescript-next
    - ms-vscode-remote.vscode-remote-extensionpack
    - msjsdiag.debugger-for-chrome
    - orta.vscode-jest
    - satokaz.vscode-bs-ctrlchar-remover
    - sidneys1.gitconfig
    - visualstudioexptteam.vscodeintellicode
    - vscoss.vscode-ansible
