# App Store: LINE, Slack

- name: Install the messaging apps
  homebrew_cask:
    accept_external_apps: true
    name: "{{ item }}"
    state: present
  with_items:
    - discord
    - messenger
    - keybase
    - skype
