- name: Install the remote tools
  homebrew:
    name:
      - git
      - gist
      - subversion
      - telnet
      - wget
    state: present

- name: Install the remote apps
  homebrew_cask:
    accept_external_apps: true
    name: "{{ item }}"
    state: present
  with_items:
    - duet
    - parallels-access
    - vysor

- name: Install the Cloud storage tools
  homebrew_cask:
    accept_external_apps: true
    name: "{{ item }}"
    state: present
  with_items:
    - adobe-creative-cloud
    - dropbox
    - omnipresence
