- name: Install the Virtualization tools
  homebrew_cask:
    accept_external_apps: true
    name: "{{ item }}"
    state: present
  with_items:
    - parallels
    - virtualbox
    - virtualbox-extension-pack
    - vagrant

- name: Collect the plugins of Vagrant
  shell: "vagrant plugin list | awk '{ print $1 }'"
  register: vagrant_plugins
  changed_when: false

- name: Install the plugins of Vagrant
  shell: "vagrant plugin install {{ item }}"
  with_items:
    - vagrant-reload
    - vagrant-parallels
  when: item not in vagrant_plugins.stdout_lines

- name: Install the Docker
  homebrew_cask:
    accept_external_apps: true
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - wercker-cli
