- name: Install the Docker
  homebrew_cask:
    name: docker
    state: present

- name: Install the Vagrant
  homebrew_cask:
    name: vagrant
    state: present

- name: Collect the plugins of Vagrant
  shell: "vagrant plugin list | awk '{ print $1 }'"
  register: vagrant_plugins
  changed_when: false

- name: Install the plugins of Vagrant
  shell: "vagrant plugin install {{ item }}"
  with_items:
    - vagrant-reload
    - vagrant-parallels
  when: item not in vagrant_plugins.stdout_lines

- name: Install the Parallels Desktop
  homebrew_cask:
    name: parallels
    state: present

- name: Install the Parallels Access
  homebrew_cask:
    name: parallels-access
    state: present

- name: Install the Virtualbox
  homebrew_cask:
    name: virtualbox
    state: present

- name: Install the Extension pack for Virtualbox
  homebrew_cask:
    name: virtualbox-extension-pack
    state: present

- name: Install the CLI for Wercker
  homebrew_cask:
    name: wercker-cli
    state: present
