- name: Unlock sudo
  lineinfile:
    dest: /etc/sudoers
    regexp: '{{ ansible_env.USER }} ALL=\(ALL\) NOPASSWD: ALL'
    line: "{{ ansible_env.USER }} ALL=(ALL) NOPASSWD: ALL"
    validate: visudo -cf %s
  become: yes

- name: Disable the Gatekeeper
  shell: spctl --master-disable
  become: true

- name: Upgrade brew.
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- import_tasks: _browsers.yml

- name: Restore the Gatekeeper
  shell: spctl --master-enable
  become: true

- name: Lock sudo
  lineinfile:
    dest: /etc/sudoers
    regexp: '{{ ansible_env.USER }} ALL=\(ALL\) NOPASSWD: ALL'
    line: ""
    validate: visudo -cf %s
  become: yes

- meta: flush_handlers
