---
- name: Create .ssh folder
  file:
    path: ~/.ssh
    state: directory
    mode: 0700

- name: SSH daemon additional settings.
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  become: true
  with_items:
    # - regexp: '^#?ChallengeResponseAuthentication\s'
    #   line: ChallengeResponseAuthentication no
    # - regexp: '^#?PasswordAuthentication\s'
    #   line: PasswordAuthentication no
    - regexp: '^#?LoginGraceTime\s'
      line: LoginGraceTime 30
    - regexp: '^#?MaxAuthTries\s'
      line: MaxAuthTries 3
    - regexp: '^#?PermitRootLogin\s'
      line: PermitRootLogin no
    - regexp: '^#?PubkeyAuthentication\s'
      line: PubkeyAuthentication yes
    - regexp: '^#?UseDNS\s'
      line: UseDNS no
